output "lb_public_url_button" {
  value = format("https://%s", var.wafrn_domain_name)
}
output "lb_public_url" {
  value = format("https://%s", var.wafrn_domain_name)
}

output "lb_public_ip" {
  value = oci_core_public_ip.wafrn_ip.ip_address
}

output "deploy_id" {
  value = random_string.deploy_id.result
}

output "deployed_to_region" {
  value = local.region_to_deploy
}

output "wafrn_admin_password" {
  value     = random_string.wafrn_admin_password.result
  sensitive = true
}

output "dns_updates" {
  value = templatefile("${path.module}/scripts/dns_config.template",
    {
      wafrn_domain_name   = var.wafrn_domain_name
      ip_address          = oci_core_public_ip.wafrn_ip.ip_address
      enable_bluesky      = var.enable_bluesky
      bluesky_domain_name = var.bluesky_domain_name
      email_domain_name   = local.email_domain_name
      has_oci_email       = (local.has_oci_email == 1)
      dns_spf_value       = local.dns_spf_value
      dns_dkim_key        = local.dns_dkim_key
      dns_dkim_value      = local.dns_dkim_value
  })
}

### Important Security Notice ###
# The private key generated by this resource will be stored unencrypted in your Terraform state file.
# Use of this resource for production deployments is not recommended.
# Instead, generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run.
output "generated_private_key_pem" {
  value     = var.generate_public_ssh_key ? tls_private_key.compute_ssh_key.private_key_pem : "No Keys Auto Generated"
  sensitive = true
}
